version: "3"

services:

  backend:
    build: ./service
    command: gunicorn vesninsoft.wsgi:application --bind 0.0.0.0:8000 --workers 3

    container_name: "backend"
    volumes:
      - static:/app/com/vesninsoft/static/
    expose:
      - "8000"

    restart: always
    depends_on:
      - psql
  
  nginx:
    build: ./nginx
    container_name: "nginx"
    volumes:
      - static:/app/com/vesninsoft/static/
    ports:
      - "80:80"
    depends_on:
      - backend

    restart: always

  psql:
    restart: always
    image: postgres:latest
    container_name: "psql"
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "vesninDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "7ZQrXgEgJC"
    ports:
      - "5432:5432"
    
  
  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "Kffb2qfvAwq@vesninsoft.ru"
      PGADMIN_DEFAULT_PASSWORD: "JHa9fUJ8wqJfv"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "50505:80"
    restart: always
  

volumes:
  static:
  postgres:
  pgadmin:

# networks:
#   postgres:
#     driver: bridge
