version: "3"

services:

  backend:
    build: ./service
    command:
      - python manage.py makemigrations &&
      - python manage.py migrate &&
      - gunicorn vesninsoft.wsgi:application --bind 0.0.0.0:8000 --workers 3
    container_name: "backend"
    volumes:
      - static:/app/com/vesninsoft/static/
    expose:
      - "8000"

    restart: always
    depends_on:
      - psql
  
  nginx:
    build: ./nginx
    container_name: "nginx"
    volumes:
      - static:/app/com/vesninsoft/static/
    ports:
      - "80:80"
    depends_on:
      - backend

    restart: always

  psql:
    restart: always
    image: postgres:latest
    container_name: "psql"
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "vesninDb"
      POSTGRES_USER: "vesninpg"
      POSTGRES_PASSWORD: "7ZQrXgEgJC"
    ports:
      - "5432:5432"

volumes:
  static:
  postgres:
