version: "3"

services:

  backend:
    build: ./service
    command: gunicorn vesninsoft.wsgi:application --bind 0.0.0.0:8000 --workers 3
    container_name: "backend"
    network_mode: "host"
    ports:
      - "8000:8000"

  # psql:
  #   restart: always
  #   image: postgres:15
  #   container_name: "psql"
  #   environment:
  #     POSTGRES_DB: "vesninDb"
  #     POSTGRES_USER: "vesninpg"
  #     POSTGRES_PASSWORD: "7ZQrXgEgJC"
  #   ports:
  #     - "5432:5432"
