version: "3"

services:

  backend:
    build: ./service
    command: gunicorn vesninsoft.wsgi:application --bind 0.0.0.0:8000 --workers 3
    container_name: "backend"
    volumes:
      - static:/app/com/vesninsoft/static/
    expose:
      - "8000"

    restart: always
  
  nginx:
    build: ./nginx
    volumes:
      - static:/app/com/vesninsoft/static/
    ports:
      - "80:8000"
    depends_on:
      - backend

    restart: always

  # psql:
  #   restart: always
  #   image: postgres:15
  #   container_name: "psql"
  #   environment:
  #     POSTGRES_DB: "vesninDb"
  #     POSTGRES_USER: "vesninpg"
  #     POSTGRES_PASSWORD: "7ZQrXgEgJC"
  #   ports:
  #     - "5432:5432"

volumes:
  static: