version: "3"

services:

  backend:
    build: ./service
    command: python manage.py runserver 0.0.0.0:8000
    container_name: "backend"
    ports:
      - "8000:8000"
    depends_on:
      - "psql"

  psql:
    restart: always
    image: postgres:15
    container_name: "psql"
    environment:
      POSTGRES_DB: "vesninDb"
      POSTGRES_USER: "vesninpg"
      POSTGRES_PASSWORD: "7ZQrXgEgJC"
    ports:
      - "5432:5432"
