# Generated by Django 4.0.2 on 2023-01-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_remove_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='corporative_username',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Корпоративный логин'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_corporative',
            field=models.BooleanField(default=False, verbose_name='Корпоративный пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
