# Generated by Django 4.0.2 on 2023-02-08 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_phone_alter_user_snils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslipsheet',
            name='bank_number',
        ),
        migrations.AddField(
            model_name='payslipsheet',
            name='payments',
            field=models.JSONField(default=dict, verbose_name='Выплаты'),
        ),
        migrations.AddField(
            model_name='payslipsheet',
            name='phone',
            field=models.CharField(default=None, max_length=12, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='payslipsheet',
            name='snils',
            field=models.CharField(default=None, max_length=11, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='payslipregistry',
            name='company',
            field=models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, related_name='Организация', to='account.company'),
        ),
    ]
