# Generated by Django 4.0.2 on 2023-01-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_corporative_username_user_is_corporative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='snils',
            field=models.CharField(max_length=11, unique=True, verbose_name='СНИЛС'),
        ),
    ]
