# Generated by Django 4.0.2 on 2023-02-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_payslipsheet_bank_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.BigIntegerField(null=True, verbose_name='КПП'),
        ),
    ]
