# Generated by Django 4.0.2 on 2023-01-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_password_alter_user_snils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='corporative_username',
        ),
    ]
