# Generated by Django 4.0.2 on 2023-02-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_company_kpp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslipregistry',
            name='inn',
        ),
    ]
